// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Adjudication = { draw_enabled: boolean, draw_movenumber: number, draw_movecount: number, draw_score: number, resign_enabled: boolean, resign_movecount: number, resign_score: number, resign_twosided: boolean, 
/**
 * fastchess `-tb` adjudication (off by default, like the reference setup).
 */
tb_enabled: boolean, tb_pieces: number, };
