// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Anomaly = { 
/**
 * warn | error
 */
level: string, message: string, tournament_id: string | null, };
