// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TState } from "./TState";

/**
 * A group of PGN games in the archive: a tournament or an external PGN file.
 */
export type ArchiveSource = { 
/**
 * "tournament" or "file".
 */
kind: string, 
/**
 * Tournament id, or the file path.
 */
id: string, label: string, path: string, files: number, games: number, state: TState | null, };
