// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Asset = { name: string, 
/**
 * browser_download_url
 */
url: string, size: bigint | null, 
/**
 * "sha256:..." when GitHub publishes it.
 */
digest: string | null, };
