// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which builds are acceptable beyond the CCRL rules.
 */
export type AssetPolicy = { 
/**
 * Accept AVX-512 / VNNI / x86-64-v4 builds (personal testing, never for CCRL).
 */
allow_avx512: boolean, 
/**
 * Rank them first when this CPU supports them.
 */
prefer_avx512: boolean, cpu_avx512: boolean, cpu_vnni: boolean, };
