// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which builds are taken. The default is "AVX2 only"; [`AssetPolicy::for_this_cpu`] adds the
 * AVX-512 builds this CPU can run (both are valid for CCRL).
 */
export type AssetPolicy = { 
/**
 * Accept AVX-512 / VNNI / x86-64-v4 builds (when the CPU runs them).
 */
allow_avx512: boolean, 
/**
 * Rank them first when this CPU supports them.
 */
prefer_avx512: boolean, cpu_avx512: boolean, cpu_vnni: boolean, };
