// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AssetVerdict = { name: string, accepted: boolean, 
/**
 * Lower is better (0 = pure AVX2).
 */
tier: number, build: string, flagged: boolean, reason: string, is_archive: boolean, is_network: boolean, };
