// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BookKind } from "./BookKind";

export type BookSpec = { kind: BookKind, count: number, seed: number, 
/**
 * Keep the standard position (518) in the book (default: excluded).
 */
include_standard: boolean, };
