// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaneCast } from "./LaneCast";
import type { LichessRound } from "./LichessRound";

export type BroadcastState = { lichess_tour_id: string | null, lichess_url: string | null, rounds: Array<LichessRound>, 
/**
 * Board number of every game broadcast (key: node|pass|round|white|black).
 */
boards: { [key in string]: number }, lichess_pushes: number, lichess_last_push: string | null, lichess_error: string | null, lanes: Array<LaneCast>, updated_at: string, };
