// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BundledEngine = { file: string, engine: string, version: string, build: string, 
/**
 * "engine", "bench" or "both".
 */
role: string, os: string, sha256: string, license: string, release_url: string, source_url: string, note: string, 
/**
 * Set when listed: the file is in this installation.
 */
present: boolean, 
/**
 * Set when listed: already in the library (same sha256 or same name and build).
 */
installed: boolean, };
