// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An opening book shipped with TorsGUI (`books/books.json`, files in the zip next to it).
 */
export type BundledBook = { file: string, name: string, 
/**
 * "pgn" or "cgb".
 */
format: string, positions: number | null, 
/**
 * fastchess reads PGN and EPD books; CGB books are for other GUIs.
 */
fastchess: boolean, author: string, description: string, terms: string, 
/**
 * Set when listed: already in the books folder.
 */
installed: boolean, };
