// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cache = { level: number, kind: string, size_kb: bigint, 
/**
 * Number of logical CPUs sharing it (per instance).
 */
shared_by: number, };
