// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CcrlEntry = { rank: number, name: string, rating: number, err_plus: number | null, err_minus: number | null, games: number | null, score: number | null, };
