// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CcrlEntry } from "./CcrlEntry";

export type CcrlList = { id: bigint | null, 
/**
 * "Blitz" | "40/15"
 */
list: string, 
/**
 * "1CPU" | "4CPU" | "8CPU" | "mixed"
 */
cpu: string, 
/**
 * "all" | "best"
 */
variant: string, source: string, fetched_at: string, entries: Array<CcrlEntry>, };
