// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CheckItem } from "./CheckItem";

export type Checklist = { items: Array<CheckItem>, 
/**
 * No failed check.
 */
ready: boolean, };
