// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Cpu = { 
/**
 * OS logical processor id (Linux cpu number; Windows: group * 64 + number).
 */
id: number, group: number, 
/**
 * Index inside the processor group (bit of the affinity mask).
 */
number: number, 
/**
 * Global physical core index.
 */
core: number, 
/**
 * 0 = first hardware thread of its core, 1 = SMT sibling...
 */
smt: number, node: number, socket: number, };
