// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CPUs a lane may use: a processor group plus a group-relative mask (Windows)
 * and the equivalent logical ids (Linux).
 */
export type CpuSet = { node: number, group: number, mask: number, cpus: Array<number>, };
