// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One engine of `engines.json`.
 */
export type CuteEngine = { name: string, 
/**
 * `command` as written in the file.
 */
command: string, working_dir: string, protocol: string, 
/**
 * Executable resolved from the command and the working folder.
 */
exe: string, args: string, 
/**
 * UCI options set in Cute Chess (Threads and Hash excluded: they come from the tournament).
 */
options: { [key in string]: string }, exists: boolean, 
/**
 * Why it cannot be imported as it is ("" = fine).
 */
note: string, };
