// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DecisiveGame = { end_time: string, result: string, white: string, black: string, opponent: string, 
/**
 * Colour of the seed.
 */
seed_color: string, moves: number, termination: string, source: string, index: number, };
