// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the user asked the runner to do (polled by the runner).
 */
export type Desired = "run" | "pause" | "stop";
