// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EloEstimate = { name: string, elo: number, lo: number, hi: number, games: number, score: number, anchored: boolean, method: string, };
