// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EloPoint } from "./EloPoint";

export type EloHistory = { player: string, players: Array<string>, points: Array<EloPoint>, };
