// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EloPoint = { 
/**
 * Games of the player so far.
 */
games: number, score_pct: number, 
/**
 * Elo difference from the score, with the 95 % interval (None when 0 % or 100 %).
 */
elo: number | null, lo: number | null, hi: number | null, 
/**
 * Performance (opponents' average rating + Elo) when every opponent has a rating.
 */
perf: number | null, };
