// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UciOption } from "./UciOption";

export type EngineEntry = { id: number | null, 
/**
 * Canonical CCRL-style display name `<Engine> <version>`.
 */
display_name: string, engine: string, version: string, author: string, 
/**
 * Path of the executable ("" when only metadata is known).
 */
path: string, dir: string, build: string, arch: string, sha256: string, 
/**
 * Repository URL (official GitHub or project site).
 */
source_url: string, release_url: string, release_tag: string, asset: string, uci_id: string, 
/**
 * Raw `uci_options.txt` content (id name + option lines).
 */
options_text: string, options: Array<UciOption>, threads_max: number | null, has_syzygy: boolean, 
/**
 * unverified | ok | failed
 */
verify_status: string, verify_detail: string, bestmove: string, notes: string, 
/**
 * Warnings such as "bmi2 build", "universal binary", "single-thread only".
 */
flags: Array<string>, used: boolean, 
/**
 * Options always sent in tournaments (Ponder=false, OwnBook=false...).
 */
default_options: { [key in string]: string }, extra_files: Array<string>, selection_reason: string, added_at: string, };
