// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The official site of an engine that is not on GitHub (commercial, GitLab, own site).
 */
export type EngineSite = { name: string, ccrl_name: string, url: string, notes: string, };
