// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EngineLive = { name: string, depth: number | null, seldepth: number | null, 
/**
 * centipawns from the engine's point of view
 */
score_cp: number | null, mate: number | null, nodes: number | null, nps: number | null, pv: Array<string>, pv_san: Array<string>, time_ms: number | null, };
