// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * CCRL rating of a library engine in one list (Blitz, 40/15, FRC).
 */
export type EngineListRating = { engine_id: number, list: string, 
/**
 * Name in the CCRL list.
 */
ccrl_name: string, rating: number, rank: number, cpus: number, games: number | null, 
/**
 * false: this version is not in the list, the rating is the latest version of the same engine.
 */
exact: boolean, };
