// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repository or homepage found for an engine family on this computer.
 */
export type EngineLink = { family: string, 
/**
 * owner/repo on GitHub ("" when only a homepage is known)
 */
repo: string, homepage: string, 
/**
 * "CCRL page" or "added by hand"
 */
source: string, updated_at: string, };
