// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PositionResult } from "./PositionResult";

export type EngineSuiteResult = { engine_id: number, name: string, results: Array<PositionResult | null>, solved: number, 
/**
 * Sum of the solve times of the solved positions (ms).
 */
solve_time_ms: number, };
