// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EpdPosition = { id: string, 
/**
 * Full FEN (halfmove and fullmove added when the EPD has none).
 */
fen: string, 
/**
 * Solutions as written in the file (SAN) and as UCI moves.
 */
bm: Array<string>, bm_uci: Array<string>, am: Array<string>, am_uci: Array<string>, 
/**
 * Mate in N moves.
 */
dm: number | null, };
