// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EvalPoint = { ply: number, 
/**
 * White's point of view, centipawns (mates clamped to ±2000)
 */
cp: number, engine: string, time_ms: bigint, depth: number | null, };
