// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EventRecord = { seq: number, ts: string, 
/**
 * info | warn | error | success
 */
level: string, kind: string, tournament_id: string | null, message: string, };
