// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportOptions = { tester: string, site: string, 
/**
 * Submission date (YYYY-MM-DD).
 */
date: string, 
/**
 * Seed player name as written in the PGNs.
 */
seed: string, 
/**
 * Player names of the tournament (seed + opponents) as written in the PGNs.
 */
players: Array<string>, threads: number, hash_mb: number, book: string, egtb: number, make_zip: boolean, };
