// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportResult = { pgn_path: string, zip_path: string | null, games: number, duplicates_dropped: number, event: string, base_name: string, players: Array<string>, };
