// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExportOptions = { tester: string, site: string, 
/**
 * Submission date (YYYY-MM-DD).
 */
date: string, 
/**
 * Seed player name as written in the PGNs.
 */
seed: string, 
/**
 * Player names of the tournament (seed + opponents) as written in the PGNs.
 */
players: Array<string>, threads: number, hash_mb: number, 
/**
 * Threads of the players that differ from `threads` (an 8CPU seed vs 1CPU opponents).
 */
threads_of: { [key in string]: number }, book: string, egtb: number, make_zip: boolean, 
/**
 * Player name in the PGNs -> how CCRL writes it (without "64-bit" / "NCPU").
 */
ccrl_names: { [key in string]: string }, 
/**
 * Where each CCRL spelling comes from (shown next to it).
 */
name_sources: { [key in string]: string }, };
