// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResolvedEngine } from "./ResolvedEngine";
import type { TournamentConfig } from "./TournamentConfig";

export type FileImport = { config: TournamentConfig | null, engines: Array<ResolvedEngine>, errors: Array<string>, warnings: Array<string>, after_import: string, notes: string, };
