// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveJudgement } from "./MoveJudgement";
import type { PositionEval } from "./PositionEval";
import type { SideSummary } from "./SideSummary";

export type GameAnalysis = { engine: string, movetime_ms: number, 
/**
 * Positions 0..=moves (position 0 = before the first move); None while not searched.
 */
positions: Array<PositionEval | null>, 
/**
 * Move i leads from position i to i+1.
 */
moves: Array<MoveJudgement | null>, white: SideSummary, black: SideSummary, };
