// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameRow = { index: number, source: string, white: string, black: string, result: string, termination: string, plies: number, end_time: string, duration_s: number | null, opening: string, round: string, };
