// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GameAnalysisConfig = { engine_id: number, start_fen: string, 
/**
 * The moves of the game (UCI).
 */
moves: Array<string>, movetime_ms: number, threads: number, hash: number, };
