// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Anomaly } from "./Anomaly";

export type Health = { runners_expected: number, runners_alive: number, fastchess_processes: number, engine_processes: number, total_ram_mb: number, free_ram_mb: number, cpu_load_pct: number, anomalies: Array<Anomaly>, engine_crashes_24h: number, time_forfeits_24h: number, failed_games_session: number, };
