// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DiskUsage } from "./DiskUsage";

export type Housekeeping = { disk: Array<DiskUsage>, unused_engines: Array<string>, superseded_engines: Array<[string, string]>, log_files: number, log_bytes: number, };
