// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Score } from "./Score";

/**
 * One `info` line with a principal variation.
 */
export type Info = { depth: number, seldepth: number | null, multipv: number, score: Score, nodes: number | null, nps: number | null, time_ms: number | null, pv: Array<string>, 
/**
 * The PV in SAN (filled by the caller that knows the position).
 */
pv_san: Array<string>, };
