// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Job = { 
/**
 * Opening partition ("home node" index, 0-based).
 */
node: number, pass: number, 
/**
 * Index of the pairing.
 */
pairing: number, round: number, 
/**
 * false: first engine of the pairing is White; true: colours reversed.
 */
reversed: boolean, 
/**
 * 1-based opening index passed to fastchess `start=`.
 */
opening: number, white: string, black: string, };
