// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KnownRepo = { name: string, 
/**
 * owner/repo on GitHub
 */
repo: string, 
/**
 * The engine's name in the CCRL lists (without version).
 */
ccrl_name: string, tested_tag: string | null, tested_asset: string | null, notes: string, 
/**
 * Best rating and full name in the CCRL Blitz list (filled by the API).
 */
blitz: [string, number] | null, 
/**
 * An engine of this family is in the library (filled by the API).
 */
installed: boolean, };
