// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LaneCast = { lane: number, port: number, 
/**
 * Connected viewers (address and logon name).
 */
viewers: Array<string>, game: string | null, error: string | null, };
