// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CpuSet } from "./CpuSet";

export type LanePlan = { 
/**
 * Opening partition index (0-based position in the tournament's node list).
 */
partition: number, node: number, lane: number, cpuset: CpuSet | null, };
