// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How long to search.
 */
export type Limit = { "MoveTime": number } | { "Depth": number } | { "Nodes": number } | "Infinite" | { "Clock": { wtime: number, btime: number, winc: number, binc: number, } };
