// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListPlacementRow } from "./ListPlacementRow";

/**
 * Where the seed lands in its CCRL list: its rating with the error band among the
 * neighbours of its CPU category.
 */
export type ListPlacement = { list: string, cpus: number, seed: string, games: number, 
/**
 * None before the first decisive result.
 */
rating: number | null, lo: number | null, hi: number | null, 
/**
 * "MLE anchored on the CCRL ratings" or "performance".
 */
method: string, 
/**
 * The rank the seed would take in the category, and how many engines are in it.
 */
would_rank: number | null, category_size: number, 
/**
 * The seed's own entry when it is already in the list (an earlier submission).
 */
listed: ListPlacementRow | null, neighbours: Array<ListPlacementRow>, };
