// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaneStatus } from "./LaneStatus";
import type { LiveGame } from "./LiveGame";

export type LiveLane = { tournament_id: string, tournament: string, lane: LaneStatus, game: LiveGame | null, elapsed_s: number | null, };
