// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineLive } from "./EngineLive";
import type { EvalPoint } from "./EvalPoint";

export type LiveGame = { white: string, black: string, fen: string, start_fen: string, moves_uci: Array<string>, moves_san: Array<string>, last_move: string | null, side_to_move: string, 
/**
 * clocks in ms at the last `go`
 */
wtime: number | null, btime: number | null, thinking: string | null, engines: Array<EngineLive>, evals: Array<EvalPoint>, log_bytes: number, };
