// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Info } from "./Info";

export type LiveAnalysis = { running: boolean, engine_id: number, engine: string, fen: string, multipv: number, 
/**
 * The best lines, first line first; scores from White's view, PVs in SAN.
 */
lines: Array<Info>, error: string | null, };
