// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type LiveRequest = { engine_id: number, fen: string, multipv: number, threads: number, hash: number, };
