// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MatchCandidate = { name: string, score: number, 
/**
 * true when the score is high enough to accept without confirmation.
 */
certain: boolean, };
