// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Engine information from a fastchess move comment
 * `{+0.21/20 2.291s, tl=102.709s, n=5716787, sd=39, nps=2506263}`.
 */
export type MoveInfo = { book: boolean, 
/**
 * Evaluation in pawns from the mover's point of view (fastchess convention).
 */
eval: number | null, 
/**
 * Mate distance when the score is `+M5` / `-M3`.
 */
mate: number | null, depth: number | null, seldepth: number | null, time_s: number | null, time_left_s: number | null, nodes: bigint | null, nps: bigint | null, note: string | null, };
