// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The judgement of one move of the game.
 */
export type MoveJudgement = { 
/**
 * "" | "inaccuracy" | "mistake" | "blunder"
 */
tag: string, 
/**
 * Centipawns lost by the mover (evaluations capped at ±1000).
 */
loss_cp: number, 
/**
 * Winning chances lost by the mover (0..2).
 */
wc_loss: number, };
