// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NominalTc = { id: string, label: string, 
/**
 * Moves per period (0 = sudden death + increment).
 */
moves: number, base_s: number, inc_s: number, };
