// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type NumaNode = { id: number, group: number, physical_cores: number, logical_cpus: number, memory_mb: bigint | null, };
