// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OpeningStat = { 
/**
 * The book moves (SAN with move numbers), or the start position of an EPD book.
 */
label: string, fen: string | null, moves: Array<string>, games: number, white_wins: number, draws: number, black_wins: number, 
/**
 * White's score in % (colour bias of the opening).
 */
white_pct: number, 
/**
 * Games played with both colours by the same two engines.
 */
pairs: number, 
/**
 * Pairs where White won both games (each engine won with White): a strong White bias.
 */
pairs_white_both: number, pairs_black_both: number, pairs_drawn: number, 
/**
 * Pairs won twice by the same engine.
 */
pairs_sweep: number, avg_plies: number | null, 
/**
 * A game to open in the viewer.
 */
example_source: string, example_index: number, };
