// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OpeningStat } from "./OpeningStat";

export type OpeningsReport = { openings: Array<OpeningStat>, games: number, white_pct: number, draw_pct: number, 
/**
 * Openings where every pair was won by White both times (at least 2 pairs).
 */
biased: number, };
