// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EpdPosition } from "./EpdPosition";

export type ParsedSuite = { positions: Array<EpdPosition>, 
/**
 * Lines that could not be read ("line 12: ...").
 */
errors: Array<string>, };
