// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Role } from "./Role";

/**
 * An engine as it takes part in a tournament (a snapshot: later edits of the
 * library entry never change a running tournament).
 */
export type Participant = { 
/**
 * Player name written in the PGN (White/Black tags).
 */
name: string, cmd: string, dir: string, 
/**
 * Extra command-line arguments for the engine (fastchess `args=`).
 */
args: string, 
/**
 * UCI options. `${THREADS}` and `${HASH}` are substituted at launch.
 */
options: { [key in string]: string }, role: Role, engine_id: number | null, has_syzygy: boolean, uci_id: string | null, 
/**
 * CCRL list rating used for ordering and statistics.
 */
rating: number | null, rating_estimated: boolean, 
/**
 * Threads of this engine when they differ from the tournament's (an 8CPU seed against
 * 1CPU opponents).
 */
threads?: number | null, 
/**
 * Hash (MB) of this engine when it differs from the tournament's.
 */
hash_mb?: number | null, };
