// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveInfo } from "./MoveInfo";

export type PgnMove = { san: string, info: MoveInfo, };
