// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlacementCheck = { 
/**
 * Logical CPUs the process may run on (as reported by the OS).
 */
cpus: Array<number>, group: number | null, mask: number | null, 
/**
 * Processes in the job / process group (fastchess + engines).
 */
processes: number, ok: boolean, detail: string, };
