// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Info } from "./Info";

export type PlayState = { active: boolean, engine: string, player: string, human_white: boolean, start_fen: string, fen: string, moves: Array<string>, sans: Array<string>, last_move: string | null, check: boolean, human_to_move: boolean, 
/**
 * Legal moves of the person: from square -> target squares.
 */
legal: { [key in string]: Array<string> }, 
/**
 * "e7e8" style pairs that promote (the board asks for the piece).
 */
promotions: Array<string>, thinking: boolean, 
/**
 * The engine's last search line, score from White's view, PV in SAN.
 */
info: Info | null, 
/**
 * Remaining time (ms) when there is a clock.
 */
white_ms: number | null, black_ms: number | null, base_ms: number, inc_ms: number, movetime_ms: number, 
/**
 * "*" while playing, else 1-0 / 0-1 / 1/2-1/2.
 */
result: string, termination: string, error: string | null, };
