// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PlayConfig = { engine_id: number, 
/**
 * The person plays White.
 */
human_white: boolean, 
/**
 * Clock: base and increment (ms). A base of 0 = the engine thinks `movetime_ms` per move
 * and the person has no clock.
 */
base_ms: number, inc_ms: number, movetime_ms: number, 
/**
 * Empty = the standard start position.
 */
start_fen: string, threads: number, hash: number, 
/**
 * Extra UCI options (UCI_LimitStrength / UCI_Elo, Skill Level…).
 */
options: { [key in string]: string }, player_name: string, };
