// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Score } from "./Score";

export type PositionResult = { bestmove: string, bestmove_san: string, score: Score, depth: number, solved: boolean, 
/**
 * When the engine found the solution and kept it to the end (ms).
 */
solved_at_ms: number | null, nodes: number | null, error: string | null, };
