// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Score } from "./Score";

/**
 * The engine's view of one position of the game.
 */
export type PositionEval = { 
/**
 * White's point of view.
 */
score: Score, best_uci: string, best_san: string, pv_san: Array<string>, depth: number, };
