// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PostContext = { 
/**
 * Seed export name, e.g. "Triumviratus 7.0 64-bit 8CPU".
 */
seed_export: string, 
/**
 * "gauntlet", "round robin", "match".
 */
kind_label: string, total_games: number, expected_games: number, opponents: number, games_per_opponent: number, threads: number, hash_mb: number, tc: string, ccrl_list: string, book: string, egtb: number, 
/**
 * Display name of the next tournament in the queue ("Stockfish 19 8CPU gauntlet").
 */
next: string | null, expected_finish: string | null, engines: Array<string>, 
/**
 * One random opening per game instead of each opening twice with colours reversed.
 */
random_openings: boolean, };
