// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PowerInfo = { plan: string, 
/**
 * Minimum processor state on AC (Windows) in percent.
 */
min_processor_state: number | null, governor: string | null, current_mhz: number | null, max_mhz: number | null, warnings: Array<string>, };
