// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Progress = { done: number, expected: number, pct: number, 
/**
 * games per hour over the last hour (rolling window)
 */
rate_per_hour: number | null, avg_game_s: number | null, eta_s: number | null, eta_at: string | null, lanes: number, };
