// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RatingLookup = { name: string, list_name: string | null, rating: number | null, estimated: boolean, rank: bigint | null, note: string, };
