// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Asset } from "./Asset";

export type Release = { tag: string, name: string, prerelease: boolean, draft: boolean, published_at: string | null, html_url: string, assets: Array<Asset>, 
/**
 * "api" | "redirect+html"
 */
via: string, };
