// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RenameReport = { pgn_tags: number, files: Array<string>, config_changed: boolean, dry_run: boolean, };
