// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How a name of the file was matched in the engine library.
 */
export type ResolvedEngine = { input: string, role: string, engine_id: number | null, name: string | null, 
/**
 * "exact", "approximate", "latest version" or "not found".
 */
how: string, alternatives: Array<string>, };
