// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Row = { name: string, games: number, wins: number, draws: number, losses: number, score: number, pct: number, 
/**
 * Elo difference from the score (merge_results.py), None when infinite.
 */
elo: number | null, elo_err: number | null, white_games: number, black_games: number, 
/**
 * Rating of the opponent (list rating) when known.
 */
rating: number | null, rating_estimated: boolean, 
/**
 * Performance = opponent rating + elo diff.
 */
performance: number | null, };
