// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LaneStatus } from "./LaneStatus";

export type RunnerStatus = { pid: number, host: string, session_started: bigint, lanes: Array<LaneStatus>, queued: number, done: number, expected: number, played_this_session: number, failed_this_session: number, 
/**
 * (unix time, games done) samples for rolling games/hour.
 */
progress: Array<[bigint, number]>, warnings: Array<string>, retry: number, phase: string, };
