// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Score from the side to move's point of view.
 */
export type Score = { cp: number | null, 
/**
 * Moves to mate (negative: the side to move is mated).
 */
mate: number | null, };
