// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetVerdict } from "./AssetVerdict";

export type Selection = { chosen: string | null, build: string, flagged: boolean, ccrl_ok: boolean, reason: string, 
/**
 * Extra files to download with the binary (networks shipped separately).
 */
extra: Array<string>, verdicts: Array<AssetVerdict>, };
