// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adjudication } from "./Adjudication";

export type Settings = { tester_name: string, site: string, engines_dir: string, books_dir: string, tablebases_dir: string, output_dir: string, default_book: string, syzygy_path: string, 
/**
 * Gaviota tablebases, passed to engines that have a Gaviota path option.
 */
gaviota_path: string, 
/**
 * Nalimov tablebases, passed to engines that have a Nalimov path option.
 */
nalimov_path: string, 
/**
 * Scorpio bitbases (egbbdll and the egbb files), passed to engines with an egbb path option.
 */
egbb_path: string, fastchess_version: string, 
/**
 * Empty = the managed download in `<workspace>/tools/fastchess`.
 */
fastchess_path: string, hash_per_thread_mb: number, adjudication: Adjudication, theme: string, 
/**
 * Windows: launch runners through a Task Scheduler task.
 */
use_task_scheduler: boolean, 
/**
 * Resume tournaments that were running when the machine went down.
 */
auto_resume: boolean, tc_base_formula: string, tc_inc_formula: string, default_factor: number, 
/**
 * Default rating gap 8CPU - 1CPU when an engine has no own history.
 */
default_cpu_gap: number, github_token: string, git_sync_dir: string, post_template_finished: string, post_template_announcement: string, post_template_progress: string, log_retention_days: number, 
/**
 * Before 0.6.3 (AVX-512 as a personal option): kept for old settings files, unused.
 */
allow_avx512: boolean, prefer_avx512: boolean, 
/**
 * Downloads take the AVX2 build even when this CPU runs AVX-512 (CCRL accepts both).
 */
avx2_only: boolean, 
/**
 * PGN files or folders outside the workspace shown in the game archive.
 */
archive_paths: Array<string>, 
/**
 * Lichess API token (scopes study:read, study:write) for live broadcasts.
 */
lichess_token: string, 
/**
 * Visibility of new Lichess broadcasts: public, unlisted or private.
 */
lichess_visibility: string, 
/**
 * First UDP port of the ccrl.live (TLCS-compatible) broadcast: lane N uses port + N.
 */
ccrl_live_port: number, 
/**
 * Desktop notifications (tournament finished, engine problems, queue, bench).
 */
desktop_notifications: boolean, 
/**
 * Look for a newer TorsGUI release on GitHub at start.
 */
check_updates: boolean, };
