// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adjudication } from "./Adjudication";

export type Settings = { tester_name: string, site: string, engines_dir: string, books_dir: string, tablebases_dir: string, output_dir: string, default_book: string, syzygy_path: string, fastchess_version: string, 
/**
 * Empty = the managed download in `<workspace>/tools/fastchess`.
 */
fastchess_path: string, hash_per_thread_mb: number, adjudication: Adjudication, theme: string, 
/**
 * Windows: launch runners through a Task Scheduler task.
 */
use_task_scheduler: boolean, 
/**
 * Resume tournaments that were running when the machine went down.
 */
auto_resume: boolean, tc_base_formula: string, tc_inc_formula: string, default_factor: number, 
/**
 * Default rating gap 8CPU - 1CPU when an engine has no own history.
 */
default_cpu_gap: number, github_token: string, git_sync_dir: string, post_template_finished: string, post_template_announcement: string, post_template_progress: string, log_retention_days: number, 
/**
 * Personal option: accept AVX-512 / VNNI / x86-64-v4 builds (never for CCRL).
 */
allow_avx512: boolean, 
/**
 * Personal option: pick them first when the CPU supports them.
 */
prefer_avx512: boolean, 
/**
 * PGN files or folders outside the workspace shown in the game archive.
 */
archive_paths: Array<string>, };
