// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SetupStep } from "./SetupStep";

export type SetupStatus = { steps: Array<SetupStep>, done: number, total: number, demo_engine: boolean, fastchess: boolean, 
/**
 * Demo tournaments already created (id, name, state).
 */
demos: Array<[string, string, string]>, 
/**
 * Engines shipped with this installation ("Stockfish 10", "Triumviratus 7.0").
 */
bundled: Array<string>, };
