// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SetupStep = { id: string, done: boolean, 
/**
 * What was found (e.g. "3 verified engines").
 */
detail: string, };
