// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SideSummary = { acpl: number, inaccuracies: number, mistakes: number, blunders: number, 
/**
 * 0..100, from the winning chances kept move after move.
 */
accuracy: number, };
