// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Slot of a game inside a tournament: which opening block it belongs to.
 * `node` is the opening partition ("home node"), not necessarily the node the
 * game physically ran on.
 */
export type SlotKey = { node: number, pass: number, round: number, white: string, black: string, };
