// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StageMatch } from "./StageMatch";

export type Stage = { number: number, matches: Array<StageMatch>, complete: boolean, };
