// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One match of a Swiss round or of a knockout round (`b` = None: a bye).
 */
export type StageMatch = { a: string, b: string | null, score_a: number, score_b: number, played: number, total: number, winner: string | null, 
/**
 * Knockout tiebreak pairs played (or scheduled).
 */
tiebreaks: number, };
