// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stage } from "./Stage";
import type { StageRow } from "./StageRow";

/**
 * Rounds of a Swiss or knockout tournament as far as they are known.
 */
export type StagesView = { rounds_total: number, stages: Array<Stage>, table: Array<StageRow>, champion: string | null, };
