// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Swiss table row.
 */
export type StageRow = { name: string, points: number, games: number, buchholz: number, byes: number, 
/**
 * Knockout: still in the cup.
 */
alive: boolean, };
