// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DecisiveGame } from "./DecisiveGame";
import type { EloEstimate } from "./EloEstimate";
import type { PairIssue } from "./PairIssue";
import type { Row } from "./Row";
import type { Termination } from "./Termination";

export type Standings = { seed: string, games: number, unfinished: number, duplicates: number, 
/**
 * Per-opponent rows, in the requested order.
 */
rows: Array<Row>, total: Row, white: Row, black: Row, 
/**
 * Every engine (useful for round robins).
 */
general: Array<Row>, terminations: Array<Termination>, termination_totals: { [key in string]: number }, incomplete_pairs: Array<PairIssue>, avg_duration_s: number | null, min_duration_s: number | null, max_duration_s: number | null, decisive: Array<DecisiveGame>, performance: number | null, avg_opponent_rating: number | null, elo: Array<EloEstimate>, };
