// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Suggestion = { rank: number, list_name: string, rating: number, cpus: number, family: string, installed_engine_id: number | null, installed_name: string | null, threads_ok: boolean, note: string, };
