// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SuiteRun } from "./SuiteRun";

export type SuiteProgress = { running: boolean, done: number, total: number, error: string | null, run: SuiteRun | null, };
