// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EngineSuiteResult } from "./EngineSuiteResult";
import type { EpdPosition } from "./EpdPosition";

export type SuiteRun = { id: string, suite: string, created_at: string, movetime_ms: number, threads: number, hash: number, positions: Array<EpdPosition>, engines: Array<EngineSuiteResult>, finished: boolean, };
