// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SuiteConfig = { 
/**
 * Built-in suite id, or empty with `path` / `text`.
 */
builtin: string, path: string, text: string, engines: Array<number>, movetime_ms: number, threads: number, hash: number, 
/**
 * Engines searching at the same time.
 */
concurrency: number, };
