// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TcResult = { base_s: number, inc_s: number, moves: number, 
/**
 * fastchess `tc=` string, e.g. "103+1" or "40/1352".
 */
fastchess: string, human: string, base_formula: string, inc_formula: string, };
