// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Threshold = { rank: number, target_name: string, target_rating: number, points_needed: number, games: number, pct_needed: number, reachable: boolean, };
