// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TState } from "./TState";

export type TimelineItem = { id: string, name: string, state: TState, start: string, end: string, estimated: boolean, };
