// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Cache } from "./Cache";
import type { Cpu } from "./Cpu";
import type { NumaNode } from "./NumaNode";

export type Topology = { cpu_model: string, vendor: string, sockets: number, physical_cores: number, logical_cpus: number, groups: number, nodes: Array<NumaNode>, cpus: Array<Cpu>, caches: Array<Cache>, smt: boolean, 
/**
 * Where the data came from ("GetLogicalProcessorInformationEx", "sysfs", "fallback").
 */
source: string, has_avx2: boolean, has_avx512: boolean, has_bmi2: boolean, };
