// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Adjudication } from "./Adjudication";
import type { Participant } from "./Participant";
import type { Placement } from "./Placement";
import type { TournamentKind } from "./TournamentKind";
import type { Variant } from "./Variant";

export type TournamentConfig = { name: string, kind: TournamentKind, participants: Array<Participant>, 
/**
 * Games per pairing (even: every opening is played with both colours).
 */
games_per_pairing: number, 
/**
 * Passes over all pairings: the openings of pass 2 follow those of pass 1,
 * so stopping after a pass keeps the result balanced.
 */
passes: number, 
/**
 * Passes actually played (<= passes). Lets a tournament be cut short
 * without moving the openings already assigned.
 */
play_passes: number | null, 
/**
 * NUMA nodes (opening partitions) used.
 */
nodes: Array<number>, 
/**
 * Openings per pairing, per pass, per node (derived by `split_openings`,
 * e.g. [8, 7] for 15 openings on 2 nodes).
 */
rounds_per_pass: Array<number>, lanes_per_node: number, 
/**
 * Games inside one fastchess process: always 1 in TorsGUI.
 */
concurrency: number, threads: number, hash_mb: number, 
/**
 * fastchess time control, e.g. "103+1", "1690+19", "40/900+10".
 */
tc: string, book: string, book_format: string, book_start: number, 
/**
 * One random opening per game (no colour-reversed pairs): fastchess `order=random`
 * with `-srand opening_seed`, so a game keeps its opening when the tournament resumes.
 */
random_openings?: boolean, opening_seed: number, event: string, site: string, syzygy_path: string, adjudication: Adjudication, extra_args: Array<string>, placement: Placement, log_level: string, 
/**
 * CCRL list the tournament is meant for ("Blitz", "40/15").
 */
ccrl_list: string, 
/**
 * Maximum automatic retries when the tournament ends cleanly with games missing.
 */
max_retries: number, 
/**
 * Attempts per slot within one runner session before giving up on it.
 */
max_slot_attempts: number, 
/**
 * fastchess binary override (empty = the managed one).
 */
fastchess: string, startup_ms: number, variant: Variant, };
