// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Desired } from "./Desired";
import type { TState } from "./TState";
import type { TournamentConfig } from "./TournamentConfig";
import type { JsonValue } from "./serde_json/JsonValue";

export type TournamentRecord = { id: string, name: string, state: TState, desired: Desired, config: TournamentConfig, created_at: string, started_at: string | null, finished_at: string | null, 
/**
 * Position in the queue (lower first), None when not queued.
 */
queue_pos: number | null, retries: number, runner_pid: number | null, 
/**
 * Unix timestamp of the last runner heartbeat.
 */
heartbeat: number | null, expected_games: number, done_games: number, last_error: string | null, imported: boolean, 
/**
 * Extra PGN sources (imported legacy tournaments).
 */
status: JsonValue | null, };
