// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Progress } from "./Progress";
import type { TournamentRecord } from "./TournamentRecord";

export type TournamentSummary = { record: TournamentRecord, progress: Progress, runner_alive: boolean, seed: string, score_line: string | null, 
/**
 * A completed knockout whose games no longer decide it (a tie that 0.7.4 and earlier gave
 * to the higher seed after 3 tiebreaks): it can be resumed to play the tiebreaks.
 */
unfinished: boolean, };
