// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Progress } from "./Progress";
import type { TournamentRecord } from "./TournamentRecord";

export type TournamentSummary = { record: TournamentRecord, progress: Progress, runner_alive: boolean, seed: string, score_line: string | null, };
