// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UciOption = { name: string, kind: string, default: string | null, min: bigint | null, max: bigint | null, vars: Array<string>, };
