// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAsset = { name: string, url: string, size: number, 
/**
 * "sha256:…" as published by GitHub, when known.
 */
digest: string | null, };
