// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserPieceSet = { name: string, 
/**
 * "wP" → data URI
 */
pieces: { [key in string]: string }, };
