// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type VerifyResult = { ok: boolean, uciok: boolean, readyok: boolean, id_name: string, id_author: string, bestmove: string, depth: number | null, seconds: number, options_text: string, tail: Array<string>, error: string | null, sha256: string, bitness: string, };
