// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveInfo } from "./MoveInfo";

export type ViewerPly = { san: string, uci: string, fen: string, info: MoveInfo, 
/**
 * White's point of view, centipawns (None for book moves)
 */
eval_cp: number | null, };
