// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ViewerPly } from "./ViewerPly";

export type ViewerGame = { headers: Array<[string, string]>, start_fen: string, plies: Array<ViewerPly>, result: string, error: string | null, };
