// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WizardPreview = { pairings: number, games_per_pairing: number, total_games: number, rounds_per_pass: Array<number>, openings_used: number, last_opening: number, concurrent_games: number, busy_threads: number, physical_cores: number, ram_needed_mb: number, ram_total_mb: number, est_game_s: number, eta_s: number, errors: Array<string>, warnings: Array<string>, first_command: string, event_example: string, };
